version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: y18n
    versions:
    - 4.0.1
    - 4.0.2
  - dependency-name: "@graphql-codegen/cli"
    versions:
    - 1.20.1
    - 1.21.1
    - 1.21.2
    - 1.21.3
  - dependency-name: "@graphql-codegen/typescript-operations"
    versions:
    - 1.17.14
    - 1.17.15
  - dependency-name: "@graphql-codegen/typescript"
    versions:
    - 1.20.2
    - 1.21.0
    - 1.21.1
  - dependency-name: elliptic
    versions:
    - 6.5.3
