version: 2.1

executors:
  node:
    docker:
      - image: circleci/node:13
    working_directory: ~/app

jobs:
  checkout_code:
    executor: node
    steps:
      - checkout
      - persist_to_workspace:
          root: ~/app
          paths:
            - ./*

  dependencies:
    executor: node
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Install dependencies
          command: yarn install --frozen-lockfile
      - persist_to_workspace:
          root: ~/app
          paths:
            - node_modules

  build:
    executor: node
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Build
          command: yarn run build
      - persist_to_workspace:
          root: ~/app
          paths:
            - dist

  lint:
    executor: node
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Lint
          command: yarn run lint

  deploy:
    executor: node
    steps:
      - attach_workspace:
          at: .
      - add_ssh_keys:
          fingerprints:
            - "0d:d4:55:3c:86:5a:33:e1:cd:85:d8:c6:da:4f:05:6d"
      - run: "git config --global user.email ${GITHUB_USER_EMAIL}"
      - run: "git config --global user.name ${GITHUB_USER_NAME}"
      - run:
          name: Deploy to GH Pages
          command: yarn gh-pages -d dist

workflows:
  version: 2
  build_test_lint:
    jobs:
      - checkout_code
      - dependencies:
          requires:
            - checkout_code
      - build:
          requires:
            - dependencies
      - lint:
          requires:
            - dependencies
      - deploy:
          requires:
            - build
            - lint
          filters:
            branches:
              only: master
