version: 2.1

executors:
  node:
    docker:
      - image: circleci/node:13
    working_directory: ~/app

jobs:
  checkout_code:
    executor: node
    steps:
      - checkout
      - persist_to_workspace:
          root: ~/app
          paths:
            - ./*

  dependencies:
    executor: node
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Install dependencies
          command: yarn install --frozen-lockfile
      - persist_to_workspace:
          root: ~/app
          paths:
            - node_modules

  build:
    executor: node
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Build
          command: yarn run build
      - persist_to_workspace:
          root: ~/app
          paths:
            - dist

  lint:
    executor: node
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Lint
          command: yarn run lint

  deploy:
    executor: node
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Create .ssh directory
          command: mkdir ~/.ssh
      - run:
          name: Trust server host
          command: echo "|1|U3InK5l+EYlRV8VYbf4X/Uy7DXQ=|soYWIYsE935mPyEJfiDmQvEoTd4= ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAq2A7hRGmdnm9tUDbO9IDSwBK6TbQa+PXYPCPy6rbTrTtw7PHkccKrpp0yVhp5HdEIcKr6pLlVDBfOLX9QUsyCOV0wzfjIJNlGEYsdlLJizHhbn2mUjvSAHQqZETYP81eFzLQNnPHt4EVVUh7VfDESU84KezmD5QlWpXLmvU31/yMf+Se8xhHTvKSCZIFImWwoG6mbUoWf9nzpIoaSjB+weqqUUmpaaasXVal72J+UX2B+2RPW3RcT0eOzQgqlJL3RKrTJvdsjE3JEAvGq3lGHSZXy28G3skua2SmVi/w4yCE6gbODqnTWlg7+wC604ydGXA8VJiS5ap43JXiUFFAaQ==" >> ~/.ssh/known_hosts
      - run: 'git config --global user.email sayhi@circleci.com'
      - run: 'git config --global user.name CircleCI'
      - add_ssh_keys:
          fingerprints:
            - 4f:08:67:2d:f8:d3:03:8c:19:ea:30:55:7d:c6:d3:57
      - run:
          name: Deploy to GH Pages
          command: yarn gh-pages -d dist

workflows:
  version: 2
  build_test_lint:
    jobs:
      - checkout_code
      - dependencies:
          requires:
            - checkout_code
      - build:
          requires:
            - dependencies
      - lint:
          requires:
            - dependencies
      - deploy:
          requires:
            - build
            - lint
          filters:
            branches:
              only: master
