name: dependabot

on:
  pull_request_target:
    types:
      - opened
      - reopened
      - synchronize
    branches: [master]

jobs:
  automerge:
    if: ${{ github.actor == 'dependabot[bot]' }}
    needs:
      - labeller

    runs-on: ubuntu-latest

    steps:
      - name: approve pr
        run: gh pr review --approve "$PR_URL"
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: mark pr as auto-mergeable
        run: gh pr merge --squash --auto "$PR_URL"
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
